In [24]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import top10Dapps

dapps = top10Dapps.top_10_dapps

for dapp in dapps:
  df = pd.read_csv('/content/'+dapp+'.csv')
  trainDF, testDF = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)

  y_train = trainDF['last_sale_price']
  X_train = trainDF.drop(columns=['last_sale_price','TOKEN_ID'])

  y_test = testDF['last_sale_price']
  X_test = testDF.drop(columns=['last_sale_price','TOKEN_ID'])

  data_dmatrix = xgb.DMatrix(data=X_train, label=y_train)
  params = {"objective":'reg:squarederror', "colsample_bytree":0.2, "learning_rate":0.009, "max_depth":20, "alpha":16}
  xg_m = xgb.train(params=params, dtrain=data_dmatrix, num_boost_round=100)

  data_dmatrix_test = xgb.DMatrix(data=X_test)
  preds = xg_m.predict(data_dmatrix_test)

  #print(dapp)
  print(np.sqrt(mean_squared_error(preds, y_test)))

  print(preds)
  newDF = df[['rarity','counts']]
  data_dmatrix_test = xgb.DMatrix(data=newDF)

  predPrice = xg_m.predict(data_dmatrix_test)
  df['predicted_price'] = predPrice

  df.to_csv('/content/predicted/' + dapp +'.csv')

    

790.3958857591853
[59.094353   1.8586352 13.534304  ... 11.585411  13.659517   7.7758417]
12.285062000742043
[8.794737  6.000505  6.011629  ... 5.5608087 5.7131276 6.8636193]
4.770217931267349
[2.6506195 2.7792892 2.7792892 ... 3.398477  2.9092612 3.6022935]
6.025474931116748
[3.5882468 3.7203445 3.1554718 ... 2.5832942 2.0500374 2.7047749]
1.2912290992363078
[0.6967511 0.9112344 0.5687364 ... 0.570827  0.9112344 0.5687364]
1.0643283523976397
[0.708461  0.5591215 0.7197373 ... 0.7176547 0.7901602 0.7148603]
433.0671773218092
[1.4527044 1.9853224 1.2994084 ... 1.2857194 1.4143779 1.2885499]
0.683132517674208
[0.79127544 0.8171613  0.8171613  ... 0.8171613  0.86525726 0.66180897]
167.06479595791689
[7.136099  2.7967682 2.8107717 ... 2.6019745 2.6019745 6.666811 ]
